language: python

python:
- '3.7-dev'

install:
- pip install -r requirements.txt

script:
- export PYTHONPATH=$PYTHONPATH:.
- py.test -v tests --cov transporter --durations=10

after_success:
- coveralls

env:
